// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Only Android is supported in this app
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATGkikPws0W1_HwTQeYF56KEgf4IxbAY4',
    appId: '1:914410787261:android:c58971155f03e0c06542d4',
    messagingSenderId: '914410787261',
    projectId: 'digital-detox-d738f',
    storageBucket: 'digital-detox-d738f.firebasestorage.app',
  );
}
